server:
  port: 8085
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://${EUREKA:localhost}:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin, Access-Control-Allow-Credentials
      routes:
        - id: backend-estudiantes-service
          uri: lb://backend-estudiantes-service
          predicates:
            - Path=/estudiante/**