server:
  port: 8081
spring:
  application:
    name: backendconfig-service
#  cloud:
#    config:
#      server:
#        git:
#          default-label: master
#          uri: https://github.com/SimonSaezCorrea/Mingeso-Tingeso-Ayudantia
#          search-paths: "Unidad 2/Aplicación-microservicio-básico/config-data"
