apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendconfig-deployment
  labels:
    app: backendconfig-deployment
spec:
  selector:
    matchLabels:
      app: backendconfig-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: backendconfig-deployment
    spec:
      containers:
        - name: topeducation-config-mysql
          image: alexandra26/topeducation-config-mysql:latest
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: backendconfig-service
  labels:
    app: backendconfig-service
spec:
  selector:
    app: backendconfig-deployment
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer