apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-gateway-deployment
  labels:
    app: backend-gateway-deployment
spec:
  selector:
    matchLabels:
      app: backend-gateway-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-gateway-deployment
    spec:
      containers:
        - name: topeducation-gateway-mysql
          image: alexandra26/topeducation-gateway-mysql:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://backendconfig-service:8081
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://backend-eureka-service:8761
            - name: eureka.instance.preferIpAddress
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-gateway-service
  labels:
    app: backend-gateway-service
spec:
  selector:
    app: backend-gateway-deployment
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: LoadBalancer