apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
type: Opaque
data:
  MYSQL_USER: cm9vdA==
  MYSQL_PASSWORD: aG9sYTEyMzQ=

---

apiVersion: v1
kind: Secret
metadata:
  name: mysql-root-credentials
type: Opaque
data:
  MYSQL_ROOT_USER: cm9vdA==
  MYSQL_ROOT_PASSWORD: aG9sYTEyMzQ=